### ISSUE TITLE
Deployment Bucket

### ISSUE THREAD

**Issue by singledigit** [SAPessi/serverless-sam#1]
It is throwing a `Deployment bucket is not in the same region as the lambda function`. However, at this stage in the game it should not even be interacting with AWS or even the CLI, right?

I added `--profile foo` just in case... same error.
<img width="914" alt="screen shot 2017-05-05 at 12 46 10 pm" src="https://cloud.githubusercontent.com/assets/897170/25759717/dee32518-3190-11e7-947c-a9a08774e124.png">

**Comment by sapessi** [comment]
The plugin uses the AwsDeploy plugin to prepare the artifacts: https://github.com/SAPessi/serverless-sam/blob/master/index.js#L155. I'll try to figure out which step is generating the error and see if I can skip it.

**Comment by sapessi** [comment]
Can you confirm which version of serverless are you testing with? I'm using 1.12.1:

```
$ serverless --version
1.12.1
```

**Comment by singledigit** [comment]
`$ serverless --version = 1.12`

Have updated to 1.12.1 and still have same error

**Comment by sapessi** [comment]
Actually, I would like to fix this for older versions too. Can you share parts of your serverless.yml file? At least where the deployment bucket is configured? I suspect many other people will run into this.

**Comment by sapessi** [comment]
Then perhaps it is something I have not tested in the `serverless.yml` options. Can you share your provider settings?

**Comment by sapessi** [comment]
Ok, I've figured out where the error is happening. When you specify a bucket name serverless tries to locate it when I call the `generateCoreTemplate` method. I need to call this before I can generate the sam. Let me see if there's a way around.

https://github.com/serverless/serverless/blob/master/lib/plugins/aws/package/lib/generateCoreTemplate.js#L28

**Comment by sapessi** [comment]
Fixed and deployed version 0.0.2 of the library. Let me know if this works.

**Comment by sapessi** [comment]
Fix confirmed, closing this issue.
