### ISSUE TITLE
Support for SQS events

### ISSUE THREAD

**Issue by paulozenida** [SAPessi/serverless-sam#30]
A pull request has been created here: https://github.com/SAPessi/serverless-sam/pull/31
Thanks.

**Comment by paulozenida** [comment]
I believe the necessary changes are, basically, the following:

lib/events/events.js
`
...
const IoTEventConverter = require('./IoTEventConverter');
const SqsEventConverter = require('./SqsEventConverter'); // ADDED

module.exports.getEventConverter = (type, serverless) => {
...

  let converter = null;
  switch (type.toLowerCase()) {
    case "sqs":
      converter = new SqsEventConverter(serverless);
      break;
...
  }
`

And add the SqsEventConverter.js file, similarly to:
`
'use strict'

const utils = require('../utils');
const randomstring = require('randomstring');

class SqsEventConverter {
  constructor(serverless) {
    this.serverless = serverless;
  }

  getEventType() {
    return "SQS";
  }

  convertEvent(event, targetResourceName) {
    let eventData = {
        Queue: ""
    };
    let resources = {};

    if (typeof(event) === "string") {
      // pre-existing SQS topic
      if (event.startsWith("anr:aws")) {
        eventData.QueueName = event;
      } else { // we want to create a new queue
        const resourceName = utils.stringToResourceName(this.serverless.service.service) + "SqsQueue" + randomstring.generate(5);
        resources[resourceName] = this.createQueueResource(resourceName, event);
      }
    } else { // it's an object
      if (event.arn) {
        eventData.Queue = event.arn;
      } else {
        if (event.topicName) {
          const resourceName = utils.stringToResourceName(this.serverless.service.service) + "SqsQueue" + randomstring.generate(5);
          resources[resourceName] = this.createQueueResource(resourceName, event);
          if (event.displayName) {
            resources[resourceName].Properties["DisplayName"] = event.displayName;
          }
        }
      }
    }

    return {
      event: eventData,
      resources: resources
    };
  }

  createQueueResource(resourceName, queueName) {
    return {
      Type: "AWS::SQS::Queue",
      Properties: {
        Queue: queueName
      }
    };
  }
}

module.exports = SqsEventConverter;
`

If you prefer, I can create a new branch and make a pull request.

Thanks.

**Comment by sapessi** [comment]
Merged pull request. Resolving.
